title: "Yggdrasil Dashboard"
favicon: "https://gethomepage.dev/apple-touch-icon.png"
theme: dark
color: slate

layout:
  Apollo:
    style: row
    columns: 4
  Cerberus:
    style: row
    columns: 2
  Management:
    style: row
    columns: 2

# Expose Docker socket data and enable auto-discovery
docker:
  my-swarm:
    socket: /var/run/docker.sock
