title: "Yggdrasil Dashboard"
favicon: "https://gethomepage.dev/apple-touch-icon.png"
theme: dark
color: slate

layout:
  Media Server:
    style: row
    columns: 3
  Manga:
    style: row
    columns: 2
  Media Automation:
    style: row
    columns: 3
  Identity:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2
  AI Lab:
    style: row
    columns: 4
