name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Secrets
        env:
          CF_DNS_TOKEN: ${{ secrets.CF_DNS_API_TOKEN }}
        run: |
          chmod +x scripts/ensure_secret.sh
          echo "OLYMPUS_CF_DNS_API_TOKEN_NAME=$(echo "$CF_DNS_TOKEN" | ./scripts/ensure_secret.sh olympus_cf_dns_api_token)" >> $GITHUB_ENV

      - name: Deploy Stack
        env:
          # Environment Config
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_DOMAIN: ${{ vars.DOMAIN_NAME }}
          SONARR_API_KEY: ${{ secrets.SONARR_API_KEY }}
          RADARR_API_KEY: ${{ secrets.RADARR_API_KEY }}
          STACK_NAME: olympus
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "olympus" docker-compose.yml